---
name: Crawl
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  Crawl:
    name: Crawl
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@main

      - name: Crawl the latest IPs list.
        run: |
          curl -fsSL "https://stat.ripe.net/data/country-resource-list/data.json?resource=ir" -o ir.json
          jq -er '.data.resources.ipv4[]' ir.json > "ipv4.txt"
          python split_subnets.py ipv4.txt
          test -s "ipv4.txt"

      - name: Create Pull Request.
        if: github.event_name != 'pull_request'
        run: |
          set -x
          if [ -n "$(git status --porcelain)" ]; then
              git switch -c automatic_crawl
              git add ir.json ipv4.txt
              git config user.email "${{ github.actor }}@users.noreply.github.com"
              git config user.name "${{ github.actor }}"
              git commit -m "Automatic Crawl"
              git push --force -u origin automatic_crawl
              if [ -z "$(gh pr list --head automatic_crawl --json number --jq '.[0].number')" ]; then
                  gh pr create --fill
              fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
